services:
  mongodb:
    image: mongo:7
    container_name: digital-library-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - digital-library-data:/data/db

volumes:
  digital-library-data:
